variable "project_id" {
  description = "GCP project ID"
  type        = string
}

variable "region" {
  description = "GCP region used for regional resources"
  type        = string
  default     = "us-central1"
}

variable "bucket_name" {
  description = "Data Lake bucket name"
  type        = string
}

variable "databricks_uc_service_account" {
  description = "Service account generated by Databricks Unity Catalog"
  type        = string
}

variable "bigquery_dataset_id" {
  description = "BigQuery dataset containing the Gold tables"
  type        = string
  default     = "epidemiological_intelligence"
}

variable "bigquery_gold_table" {
  description = "Gold table consumed by the Data Science pipeline"
  type        = string
  default     = "epidemiology_climate_monthly"
}

variable "data_science_image" {
  description = "Docker image used by the Data Science Cloud Run Job"
  type        = string
}