variable "project_id" {
  description = "GCP project ID"
  type        = string
}

variable "region" {
  description = "Main resourses region"
  type        = string
  default     = "us-central"
}
variable "bucket_name" {
  description = "Data Lake bucket name"
  type        = string
}
variable "databricks_uc_service_account" {
  description = "Service account generated by Databricks Unity Catalog"
  type        = string
}